-- ANSWER 1
SELECT
	*,
	LAG(NET_TOTAL) OVER (
		PARTITION BY
			CUST_ID
		ORDER BY
			ORDER_DATE
	) AS PREV_NET_TOTAL,
	NET_TOTAL - LAG(NET_TOTAL) OVER (
		PARTITION BY
			CUST_ID
		ORDER BY
			ORDER_DATE
	) AS CHANGE
FROM
	SALES.ORDERS

-- ANSWER 2
WITH
	DIFF_CALC AS (
		SELECT
			*,
			LAG(CREATED_DATE) OVER (
				PARTITION BY
					AGENT_ID
				ORDER BY
					CREATED_DATE
			) AS PREV_CD,
			CREATED_DATE - LAG(CREATED_DATE) OVER (
				PARTITION BY
					AGENT_ID
				ORDER BY
					CREATED_DATE
			) AS DIFF
		FROM
			SUPPORT.TICKETS
	)
SELECT
	AGENT_ID,
	CREATED_DATE,
	PREV_CD,
	MIN(DIFF)
FROM
	DIFF_CALC
GROUP BY
	AGENT_ID,
	CREATED_DATE,
	PREV_CD
LIMIT
	1

-- ANSWER 3
WITH
	EMP_JOIN_DETAILS AS (
		SELECT
			FIRST_NAME AS CURR_EMP,
			STORE_ID,
			JOINING_DATE,
			LEAD(FIRST_NAME) OVER (
				PARTITION BY
					STORE_ID
				ORDER BY
					JOINING_DATE
			) AS NEXT_EMP,
			STORE_ID
		FROM
			STORES.EMPLOYEES
	)
SELECT
	*
FROM
	EMP_JOIN_DETAILS
WHERE
	NEXT_EMP IS NOT NULL

-- ANSWER 4
WITH
	WEEKLY AS (
		SELECT
			DATE_TRUNC('week', ORDER_DATE) AS WEEK,
			COUNT(*) AS ORDER_COUNT
		FROM
			SALES.ORDERS
		GROUP BY
			DATE_TRUNC('week', ORDER_DATE)
	)
SELECT
	*,
	LAG(ORDER_COUNT) OVER (
		ORDER BY
			ORDER_COUNT
	) AS PREV_ORD_CNT,
	ROUND(
		(
			ORDER_COUNT - LAG(ORDER_COUNT) OVER (
				ORDER BY
					ORDER_COUNT
			)
		) * 100.0 / NULLIF(
			LAG(ORDER_COUNT) OVER (
				ORDER BY
					ORDER_COUNT
			),
			0
		),
		2
	) AS WOW_GROWTH_PCT
FROM
	WEEKLY

-- ANSWER 5
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	DEPT_ID,
	JOINING_DATE,
	FIRST_VALUE(FIRST_NAME) OVER (
		PARTITION BY
			DEPT_ID
		ORDER BY
			JOINING_DATE
	) AS FIRST_FOUND
FROM
	STORES.EMPLOYEES

-- ANSWER 6
SELECT
	CAMPAIGN_ID,
	FIRST_VALUE(BUDGET) OVER (
		ORDER BY
			START_DATE
	) AS FIRST_BUDGET,
	LAST_VALUE(BUDGET) OVER (
		ORDER BY
			START_DATE ROWS BETWEEN UNBOUNDED PRECEDING
			AND UNBOUNDED FOLLOWING
	) AS LAST_BUDGET
FROM
	MARKETING.CAMPAIGNS

-- ANSWER 7
SELECT
	*,
	FIRST_VALUE(NET_TOTAL) OVER (
		PARTITION BY
			CUST_ID
		ORDER BY
			NET_TOTAL
	) AS SMALLEST,
	LAST_VALUE(NET_TOTAL) OVER (
		PARTITION BY
			CUST_ID
		ORDER BY
			NET_TOTAL ROWS BETWEEN UNBOUNDED PRECEDING
			AND UNBOUNDED FOLLOWING
	) AS LARGEST,
	LAST_VALUE(NET_TOTAL) OVER (
		PARTITION BY
			CUST_ID
		ORDER BY
			NET_TOTAL ROWS BETWEEN UNBOUNDED PRECEDING
			AND UNBOUNDED FOLLOWING
	) - FIRST_VALUE(NET_TOTAL) OVER (
		PARTITION BY
			CUST_ID
		ORDER BY
			NET_TOTAL
	) AS RANGE
FROM
	SALES.ORDERS

-- ANSWER 8
SELECT
	*,
	LAST_VALUE(SALARY) OVER (
		PARTITION BY
			DEPT_ID
		ORDER BY
			SALARY DESC
	)
FROM
	STORES.EMPLOYEES


SELECT
	*,
	LAST_VALUE(SALARY) OVER (
		PARTITION BY
			DEPT_ID
		ORDER BY
			SALARY DESC ROWS BETWEEN UNBOUNDED PRECEDING
			AND UNBOUNDED FOLLOWING
	)
FROM
	STORES.EMPLOYEES

-- ANSWER 9
SELECT
	*,
	NTH_VALUE(BUDGET, 2) OVER (
		ORDER BY
			BUDGET DESC ROWS BETWEEN UNBOUNDED PRECEDING
			AND UNBOUNDED FOLLOWING
	) AS SILVER
FROM
	MARKETING.CAMPAIGNS

-- ANSWER 10
WITH
	PODIUM AS (
		SELECT
			*,
			FIRST_VALUE(SALARY) OVER (
				PARTITION BY
					DEPT_ID
				ORDER BY
					SALARY DESC
			) AS GOLD,
			NTH_VALUE(SALARY, 2) OVER (
				PARTITION BY
					DEPT_ID
				ORDER BY
					SALARY DESC ROWS BETWEEN UNBOUNDED PRECEDING
					AND UNBOUNDED FOLLOWING
			) AS SILVER,
			NTH_VALUE(SALARY, 2) OVER (
				PARTITION BY
					DEPT_ID
				ORDER BY
					SALARY DESC ROWS BETWEEN UNBOUNDED PRECEDING
					AND UNBOUNDED FOLLOWING
			) AS BRONZE
		FROM
			STORES.EMPLOYEES
	)
SELECT DISTINCT
	DEPT_ID,
	SALARY,
	GOLD,
	SILVER,
	BRONZE,
	GOLD - BRONZE AS DIFF
FROM
	PODIUM

-- ANSWER 11
WITH
	RESOLUTION_TIME AS (
		SELECT
			*,
			RESOLVED_DATE - CREATED_DATE AS RESO_TIME
		FROM
			SUPPORT.TICKETS
	)
SELECT
	*,
	NTH_VALUE(RESO_TIME, 5) OVER (
		PARTITION BY
			CATEGORY
		ORDER BY
			RESO_TIME
	) AS FIFTH_FASTEST
FROM
	RESOLUTION_TIME

-- ANSWER 12
WITH
	REV_PER_STORE AS (
		SELECT
			STORE_ID,
			SUM(NET_TOTAL) AS TOTAL_REV
		FROM
			SALES.ORDERS
		GROUP BY
			STORE_ID
	),
	PODIUM AS (
		SELECT
			STORE_ID,
			TOTAL_REV,
			NTH_VALUE(TOTAL_REV, 1) OVER W AS FIRST,
			NTH_VALUE(TOTAL_REV, 2) OVER W AS SECOND,
			NTH_VALUE(TOTAL_REV, 3) OVER W AS THIRD
		FROM
			REV_PER_STORE
		WINDOW
			W AS (
				ORDER BY
					TOTAL_REV DESC ROWS BETWEEN UNBOUNDED PRECEDING
					AND UNBOUNDED FOLLOWING
			)
	)
SELECT
	*,
	FIRST - TOTAL_REV AS GAP
FROM
	PODIUM



                        -- CHALLENGES
                        
                        --(SET A)

-- ANSWER 1
WITH
	PREV AS (
		SELECT
			*,
			LAG(NET_TOTAL) OVER (
				PARTITION BY
					CUST_ID
				ORDER BY
					NET_TOTAL
			) AS PREV_TOTAL
		FROM
			SALES.ORDERS
	)
SELECT
	*,
	NET_TOTAL - PREV_TOTAL AS CHANGE
FROM
	PREV
WHERE
	NET_TOTAL - PREV_TOTAL IS NOT NULL
ORDER BY
	CHANGE DESC

-- ANSWER 2
WITH
	MONTHLY AS (
		SELECT
			DATE_TRUNC('month', ORDER_DATE) AS MONTHS,
			sum(net_total) as revenue
		FROM
			SALES.ORDERS
			group by DATE_TRUNC('month', ORDER_DATE)
	)
select *,
	(revenue -  lag(revenue) over(order by months))* 100.0 / lag(revenue) over(order by months) as mom_pct
from monthly
order by mom_pct desc

-- ANSWER 3
SELECT
	*,
	LEAD(JOINING_DATE) OVER (
		PARTITION BY
			DEPT_ID
		ORDER BY
			JOINING_DATE
	) AS NEXT_EMP_JOIN_DATE,
	LEAD(JOINING_DATE) OVER (
		PARTITION BY
			DEPT_ID
		ORDER BY
			JOINING_DATE
	) - JOINING_DATE AS JOINING_GAP
FROM
	STORES.EMPLOYEES

-- ANSWER 4
WITH
	TICKETS AS (
		SELECT
			*,
			LAG(CREATED_DATE) OVER (
				PARTITION BY
					AGENT_ID
				ORDER BY
					CREATED_DATE
			) AS PREV_TICKET_TIME
		FROM
			SUPPORT.TICKETS
		WHERE
			RESOLVED_DATE IS NOT NULL
	),
	GAP AS (
		SELECT
			*,
			CREATED_DATE - PREV_TICKET_TIME AS TIME_BW_TWO_TICKETS
		FROM
			TICKETS
		WHERE
			PREV_TICKET_TIME IS NOT NULL
	)
SELECT
	AGENT_ID,
	AVG(TIME_BW_TWO_TICKETS) AS AVG_GAP
FROM
	GAP
GROUP BY
	AGENT_ID
ORDER BY
	AVG_GAP

-- ANSWER 5
WITH
	ADD_DEPT_MATRIC AS (
		SELECT
			*,
			FIRST_VALUE(SALARY) OVER (
				PARTITION BY
					DEPT_ID
				ORDER BY
					SALARY DESC
			) AS DEPT_HIGHTES_SALARY,
			FIRST_VALUE(SALARY) OVER (
				PARTITION BY
					DEPT_ID
				ORDER BY
					SALARY ASC
			) AS DEPT_LOWEST_SALARY
		FROM
			STORES.EMPLOYEES
	)
SELECT
	*,
	ROUND(
		(
			(SALARY - DEPT_LOWEST_SALARY) * 100.0 / (DEPT_HIGHTES_SALARY - DEPT_LOWEST_SALARY)
		),
		2
	) AS PCT_OF_RANGE
FROM
	ADD_DEPT_MATRIC
	-- Perentile formula: ((value - min) / (max - min)) * 100.0

-- ANSWER 6
SELECT
	*,
	FIRST_VALUE(NET_TOTAL) OVER (
		PARTITION BY
			STORE_ID
		ORDER BY
			ORDER_DATE ASC
	) AS FIRST_STORE_ORD_AMOUNT,
	FIRST_VALUE(NET_TOTAL) OVER (
		PARTITION BY
			STORE_ID
		ORDER BY
			ORDER_DATE DESC
	) AS LAST_STORE_ORD_AMOUNT
FROM
	SALES.ORDERS

-- ANSWER 7
WITH
	BUDGET AS (
		SELECT
			*,
			FIRST_VALUE(BUDGET) OVER (
				ORDER BY
					START_DATE
			) AS FIRST_BUDGET,
			FIRST_VALUE(BUDGET) OVER (
				ORDER BY
					START_DATE DESC
			) AS LAST_BUDGET
		FROM
			MARKETING.CAMPAIGNS
	)
SELECT
	CAMPAIGN_ID,
	FIRST_BUDGET,
	LAST_BUDGET,
	CASE
		WHEN LAST_BUDGET > FIRST_BUDGET THEN 'Increasing'
		WHEN LAST_BUDGET < FIRST_BUDGET THEN 'Decreasing'
		ELSE 'FLAT'
	END AS TREND
FROM
	BUDGET

-- ANSWER 8
SELECT
	*,
	FIRST_VALUE(SALARY) OVER W AS GOLD,
	NTH_VALUE(SALARY, 2) OVER W AS SILVER,
	NTH_VALUE(SALARY, 3) OVER W AS BRONZE
FROM
	STORES.EMPLOYEES
WINDOW
	W AS (
		PARTITION BY
			DEPT_ID
		ORDER BY
			SALARY DESC ROWS BETWEEN UNBOUNDED PRECEDING
			AND UNBOUNDED FOLLOWING
	)

-- ANSWER 9
WITH
	RANKED AS (
		SELECT
			*,
			NTH_VALUE(NET_TOTAL, 1) OVER W AS LARGEST_ORDER,
			NTH_VALUE(NET_TOTAL, 2) OVER W AS SECOND_LARGEST_ORDER
		FROM
			SALES.ORDERS
		WINDOW
			W AS (
				PARTITION BY
					STORE_ID
				ORDER BY
					NET_TOTAL DESC ROWS BETWEEN UNBOUNDED PRECEDING
					AND UNBOUNDED FOLLOWING
			)
	)
SELECT
	STORE_ID,
	LARGEST_ORDER,
	SECOND_LARGEST_ORDER,
	LARGEST_ORDER - SECOND_LARGEST_ORDER AS DIFF
FROM
	RANKED

-- ANSWER 10
WITH
	STORE_REV AS (
		SELECT
			STORE_ID,
			SUM(NET_TOTAL) AS STORE_REV
		FROM
			SALES.ORDERS
		GROUP BY
			STORE_ID -- IMP
	)
SELECT
	*,
	DENSE_RANK() OVER (
		ORDER BY
			STORE_REV DESC
	) AS STORE_RANK,
	FIRST_VALUE(STORE_REV) OVER W AS TOP1,
	FIRST_VALUE(STORE_REV) OVER W - STORE_REV AS GAP_FROM_TOP1,
	NTH_VALUE(STORE_REV, 2) OVER W AS TOP2,
	NTH_VALUE(STORE_REV, 2) OVER W - STORE_REV AS GAP_FROM_TOP2,
	LAG(STORE_REV) OVER (
		ORDER BY
			STORE_REV DESC
	) AS PREV_STORE_REV
FROM
	STORE_REV
WINDOW
	W AS (
		ORDER BY
			STORE_REV DESC ROWS BETWEEN UNBOUNDED PRECEDING
			AND UNBOUNDED FOLLOWING
	)

