-- ANSWER 1

SELECT
	CASE
		WHEN E.EMPLOYEE_ID IS NOT NULL
		AND T.AGENT_ID IS NOT NULL THEN 'ACTIVE AGENT'
		WHEN E.EMPLOYEE_ID IS NOT NULL
		AND T.AGENT_ID IS NULL THEN 'EMPLOYEE - NO TICKETS'
		WHEN E.EMPLOYEE_ID IS NULL
		AND T.AGENT_ID IS NOT NULL THEN 'TICKET - INVALID AGENT'
	END AS CATEGORY,
	COUNT(*) AS COUNT
FROM
	STORES.EMPLOYEES E
	FULL JOIN SUPPORT.TICKETS T ON E.EMPLOYEE_ID = T.AGENT_ID
GROUP BY
	CASE
		WHEN E.EMPLOYEE_ID IS NOT NULL
		AND T.AGENT_ID IS NOT NULL THEN 'ACTIVE AGENT'
		WHEN E.EMPLOYEE_ID IS NOT NULL
		AND T.AGENT_ID IS NULL THEN 'EMPLOYEE - NO TICKETS'
		WHEN E.EMPLOYEE_ID IS NULL
		AND T.AGENT_ID IS NOT NULL THEN 'TICKET - INVALID AGENT'
	END
ORDER BY CATEGORY

-- ANSWER 2
SELECT
	CASE
		WHEN C.CUSTOMER_ID IS NOT NULL
		AND M.CUSTOMER_ID IS NOT NULL THEN 'IN BOTH'
		WHEN C.CUSTOMER_ID IS NOT NULL
		AND M.CUSTOMER_ID IS NULL THEN 'IN CUSTOMER ONLY'
		ELSE 'IN MEMBER ONLY'
	END AS CLASSIFICATION,
	COUNT(*) AS CUSTOMER_COUNT
FROM
	CUSTOMERS.CUSTOMERS C
	FULL JOIN LOYALTY.MEMBERS M USING (CUSTOMER_ID)
GROUP BY
	CASE
		WHEN C.CUSTOMER_ID IS NOT NULL
		AND M.CUSTOMER_ID IS NOT NULL THEN 'IN BOTH'
		WHEN C.CUSTOMER_ID IS NOT NULL
		AND M.CUSTOMER_ID IS NULL THEN 'IN CUSTOMER ONLY'
		ELSE 'IN MEMBER ONLY'
	END

-- ANSWER 3
SELECT
	CASE
		WHEN O.ORDER_ID IS NOT NULL
		AND S.SHIPMENT_ID IS NOT NULL THEN 'SHIPPED'
		WHEN O.ORDER_ID IS NOT NULL THEN 'NOT SHIPPED'
		ELSE 'DATA ERROR'
	END AS STATUS,
	COUNT(DISTINCT O.ORDER_ID) AS ORDER_COUNT
FROM
	SALES.ORDERS O
	FULL JOIN SALES.SHIPMENTS S USING (ORDER_ID)
GROUP BY
	CASE
		WHEN O.ORDER_ID IS NOT NULL
		AND S.SHIPMENT_ID IS NOT NULL THEN 'SHIPPED'
		WHEN O.ORDER_ID IS NOT NULL THEN 'NOT SHIPPED'
		ELSE 'DATA ERROR'
	END

-- ANSWER 4
SELECT
	P.PRODUCT_ID,
	P.PRODUCT_NAME,
	CASE
		WHEN P.PRODUCT_ID IS NOT NULL
		AND R.REVIEW_ID IS NULL THEN 'PRODUCT WITH NO REVIEW'
		WHEN P.PRODUCT_ID IS NULL THEN 'REVIEW WITH WRONG PRODUCTS'
	END AS PRODUCT_REVIEW
FROM
	PRODUCTS.PRODUCTS P
	FULL OUTER JOIN CUSTOMERS.REVIEWS R USING (PRODUCT_ID)
WHERE
	P.PRODUCT_ID IS NULL
	OR R.REVIEW_ID IS NULL
GROUP BY
	P.PRODUCT_ID,
	P.PRODUCT_NAME,
	CASE
		WHEN P.PRODUCT_ID IS NOT NULL
		AND R.REVIEW_ID IS NULL THEN 'PRODUCT WITH NO REVIEW'
		WHEN P.PRODUCT_ID IS NULL THEN 'REVIEW WITH WRONG PRODUCTS'
	END
ORDER BY
	P.PRODUCT_ID

-- ANSWER 5
SELECT
	O.ORDER_ID,
	C.FIRST_NAME,
	P.PRODUCT_NAME,
	OI.QUANTITY,
	OI.NET_AMOUNT,
	S.STORE_NAME,
	PA.PAYMENT_MODE
FROM
	SALES.ORDERS O
	JOIN CUSTOMERS.CUSTOMERS C ON O.CUST_ID = C.CUSTOMER_ID
	JOIN SALES.ORDER_ITEMS OI USING (ORDER_ID)
	JOIN PRODUCTS.PRODUCTS P ON OI.PROD_ID = P.PRODUCT_ID
	JOIN STORES.STORES S USING (STORE_ID)
	JOIN SALES.PAYMENTS PA USING (ORDER_ID)

-- ANSWER 6
SELECT
	B.BRAND_ID,
	B.BRAND_NAME,
	COUNT(DISTINCT P.PRODUCT_ID) AS PROD_COUNT,
	SUM(OI.NET_AMOUNT) AS TOTAL_REVENUE,
	ROUND(AVG(P.PRICE), 2) AS AVG_PRICE,
	SUM(OI.QUANTITY) AS QTY_SOLD
FROM
	CORE.DIM_BRAND B
	LEFT JOIN PRODUCTS.PRODUCTS P USING (BRAND_ID)
	LEFT JOIN SALES.ORDER_ITEMS OI ON OI.PROD_ID = P.PRODUCT_ID
GROUP BY
	B.BRAND_ID,
	B.BRAND_NAME

-- ANSWER 7
SELECT
	S.STORE_NAME,
	S.REGION_ID,
	E.EMP_COUNT,
	O.ORDER_COUNT,
	REV.REVENUE
FROM
	STORES.STORES S
	LEFT JOIN CORE.DIM_REGION R USING (REGION_ID)
	LEFT JOIN (
		SELECT
			STORE_ID,
			COUNT(EMPLOYEE_ID) AS EMP_COUNT
		FROM
			STORES.EMPLOYEES
		GROUP BY
			STORE_ID
	) E USING (STORE_ID)
	LEFT JOIN (
		SELECT
			STORE_ID,
			COUNT(ORDER_ID) AS ORDER_COUNT
		FROM
			SALES.ORDERS
		GROUP BY
			STORE_ID
	) O USING (STORE_ID)
	LEFT JOIN (
		SELECT
			STORE_ID,
			SUM(NET_TOTAL) AS REVENUE
		FROM
			SALES.ORDERS
		GROUP BY
			STORE_ID
	) REV USING (STORE_ID)

-- ANSWER 8
-- Products with orders only
-- Drops products with no sales
-- Drops orphan order_items (if any)
SELECT
	*
FROM
	PRODUCTS.PRODUCTS P
	INNER JOIN SALES.ORDER_ITEMS OI ON OI.PROD_ID = P.PRODUCT_ID;

-- All products + matching orders
-- Keeps all products (even if it has no orders)
-- If no order → oi.* = NULL
SELECT
	*
FROM
	PRODUCTS.PRODUCTS P
	LEFT JOIN SALES.ORDER_ITEMS OI ON OI.PROD_ID = P.PRODUCT_ID;

-- All products (even if it has no orders)
-- All order_items (even if it has no products)
-- Non-matching rows → NULLs on either side
SELECT
	*
FROM
	PRODUCTS.PRODUCTS P
	FULL JOIN SALES.ORDER_ITEMS OI ON OI.PROD_ID = P.PRODUCT_ID;

-- ANSWER 9
SELECT
	R.REGION_ID,
	R.REGION_NAME,
	EXTRACT(
		MONTH
		FROM
			O.ORDER_DATE
	) AS MONTH,
	SUM(O.NET_TOTAL) AS REVENUE
FROM
	SALES.ORDERS O
	LEFT JOIN STORES.STORES S USING (STORE_ID)
	LEFT JOIN CORE.DIM_REGION R USING (REGION_ID)
GROUP BY
	R.REGION_ID,
	R.REGION_NAME,
	EXTRACT(
		MONTH
		FROM
			O.ORDER_DATE
	)

-- ANSWER 10
SELECT
	COUNT(*) AS ALL,
	COUNT(DISTINCT O.ORDER_ID) AS ORDERS,
	COUNT(DISTINCT P.PAYMENT_ID) AS PAYMENTS
FROM
	SALES.ORDERS O
	LEFT JOIN SALES.ORDER_ITEMS OI USING (ORDER_ID)
	LEFT JOIN SALES.PAYMENTS P USING (ORDER_ID)
	-- count(DISTINCT o.order_id) is count of all unique orders
	-- count(DISTINCT p.payment_id) is count of all unique payments made
	-- count(*) is count of combinations of order × items × payments

-- ANSWER 11
SELECT
	COUNT(O.ORDER_ID) AS TOTAL_ORDERS,
	COUNT(P.PAYMENT_ID) AS TOTAL_PAYMENTS
FROM
	SALES.ORDERS O
	LEFT JOIN SALES.PAYMENTS P USING (ORDER_ID)
-- NO FAN OUT HERE

-- ANSWER 12
SELECT
	*
FROM
	STORES.STORES S
	LEFT JOIN STORES.EMPLOYEES E USING (STORE_ID)
	LEFT JOIN HR.ATTENDANCE HA USING (EMPLOYEE_ID)

-- FAN OUT OCCURS AFTER JOINING HR.ATTENDANCE  

-- ANSWER 13

                        -- METHOD 1(BUGGY)
SELECT
	C.CUSTOMER_ID,
	COUNT(O.ORDER_ID) AS ORDER_COUNT,
	COUNT(T.TICKET_ID) AS TICKET_COUNT
FROM
	CUSTOMERS.CUSTOMERS C
	LEFT JOIN SALES.ORDERS O ON C.CUSTOMER_ID = O.CUST_ID
	LEFT JOIN SUPPORT.TICKETS T USING (CUSTOMER_ID)
GROUP BY
	C.CUSTOMER_ID
ORDER BY
	C.CUSTOMER_ID

                        -- METHOD 2(FIXED)

SELECT
	C.CUSTOMER_ID,
	O.ORDER_COUNT,
	COALESCE(T.TICKET_COUNT, 0) AS TICKET_COUNT
FROM
	CUSTOMERS.CUSTOMERS C
	LEFT JOIN (
		SELECT
			CUST_ID,
			COUNT(ORDER_ID) AS ORDER_COUNT
		FROM
			SALES.ORDERS
		GROUP BY
			CUST_ID
	) O ON C.CUSTOMER_ID = O.CUST_ID
	LEFT JOIN (
		SELECT
			CUSTOMER_ID,
			COUNT(TICKET_ID) AS TICKET_COUNT
		FROM
			SUPPORT.TICKETS
		GROUP BY
			CUSTOMER_ID
	) T USING (CUSTOMER_ID)
ORDER BY
	C.CUSTOMER_ID

-- ANSWER 14
SELECT
	CASE
		WHEN E.DEPT_ID IS NOT NULL
		AND D.DEPT_ID IS NOT NULL THEN 'Matches'
		WHEN E.DEPT_ID IS NOT NULL THEN 'Dept Only'
		ELSE 'Employee Only'
	END AS CLASSIFICATION,
	COUNT(E.EMPLOYEE_ID)
FROM
	CORE.DIM_DEPARTMENT D
	FULL JOIN STORES.EMPLOYEES E ON E.DEPT_ID = D.DEPT_ID
GROUP BY
	CASE
		WHEN E.DEPT_ID IS NOT NULL
		AND D.DEPT_ID IS NOT NULL THEN 'Matches'
		WHEN E.DEPT_ID IS NOT NULL THEN 'Dept Only'
		ELSE 'Employee Only'
	END

-- ANSWER 15
SELECT
	P.PRODUCT_ID,
	COALESCE(OI.ORDER_ITEM_ID, 0) AS ORDER_ITEM_ID,
	CASE
		WHEN OI.ORDER_ITEM_ID IS NULL THEN 'Product Never Ordered'
		ELSE 'In-Valid product ID'
	END AS CLASSIFICATION
FROM
	PRODUCTS.PRODUCTS P
	FULL JOIN SALES.ORDER_ITEMS OI ON OI.PROD_ID = P.PRODUCT_ID
WHERE
	OI.ORDER_ITEM_ID IS NULL
	OR P.PRODUCT_ID IS NULL

-- ANSWER 16
SELECT
	CASE
		WHEN C.CUSTOMER_ID IS NOT NULL
		AND M.CUSTOMER_ID IS NOT NULL THEN 'IN BOTH'
		WHEN C.CUSTOMER_ID IS NOT NULL
		AND M.CUSTOMER_ID IS NULL THEN 'IN CUSTOMER ONLY'
		ELSE 'IN MEMBER ONLY'
	END AS CLASSIFICATION,
	COUNT(*) AS CUSTOMER_COUNT
FROM
	CUSTOMERS.CUSTOMERS C
	FULL JOIN LOYALTY.MEMBERS M USING (CUSTOMER_ID)
GROUP BY
	CASE
		WHEN C.CUSTOMER_ID IS NOT NULL
		AND M.CUSTOMER_ID IS NOT NULL THEN 'IN BOTH'
		WHEN C.CUSTOMER_ID IS NOT NULL
		AND M.CUSTOMER_ID IS NULL THEN 'IN CUSTOMER ONLY'
		ELSE 'IN MEMBER ONLY'
	END

-- ANSWER 17
SELECT
	CASE
		WHEN O.ORDER_ID IS NOT NULL
		AND S.ORDER_ID IS NOT NULL THEN 'Shipped Order'
		WHEN O.ORDER_ID IS NOT NULL THEN 'Unshipped Order'
		ELSE 'Orphan Order'
	END AS CLASSIFICATION,
	COUNT(*) AS ORDER_COUNT
FROM
	SALES.ORDERS O
	FULL JOIN SALES.SHIPMENTS S ON S.ORDER_ID = O.ORDER_ID
GROUP BY
	CASE
		WHEN O.ORDER_ID IS NOT NULL
		AND S.ORDER_ID IS NOT NULL THEN 'Shipped Order'
		WHEN O.ORDER_ID IS NOT NULL THEN 'Unshipped Order'
		ELSE 'Orphan Order'
	END

-- ANSWER 18
SELECT
	O.ORDER_ID,
	C.FIRST_NAME,
	QTY.PRODUCT_NAME,
	QTY.QTY_SOLD,
	O.NET_TOTAL,
	S.STORE_NAME,
	COALESCE(PAY.PAYMENT_MODE, 'Not Paid') AS PAYMENT_MODE
FROM
	SALES.ORDERS O
	LEFT JOIN CUSTOMERS.CUSTOMERS C ON O.CUST_ID = C.CUSTOMER_ID
	LEFT JOIN (
		SELECT
			ORDER_ID,
			COUNT(QUANTITY) AS QTY_SOLD,
			STRING_AGG(P.PRODUCT_NAME, ', ') AS PRODUCT_NAME
		FROM
			SALES.ORDER_ITEMS OI
			LEFT JOIN PRODUCTS.PRODUCTS P ON OI.PROD_ID = P.PRODUCT_ID
		GROUP BY
			ORDER_ID
	) QTY USING (ORDER_ID)
	LEFT JOIN STORES.STORES S USING (STORE_ID)
	LEFT JOIN SALES.PAYMENTS PAY USING (ORDER_ID)
ORDER BY O.ORDER_ID

-- ANSWER 19
SELECT
	R.REGION_ID,
	R.REGION_NAME,
	S.TOTAL_STORES,
	E.TOTAL_EMPLOYEES,
	O.TOTAL_ORDERS
FROM
	CORE.DIM_REGION R
	LEFT JOIN (
		SELECT
			REGION_ID,
			COUNT(STORE_ID) AS TOTAL_STORES
		FROM
			STORES.STORES
		GROUP BY
			REGION_ID
	) S USING (REGION_ID)
	LEFT JOIN (
		SELECT
			S.REGION_ID,
			COUNT(E.EMPLOYEE_ID) AS TOTAL_EMPLOYEES
		FROM
			STORES.EMPLOYEES E
			LEFT JOIN STORES.STORES S USING (STORE_ID)
		GROUP BY
			S.REGION_ID
	) E USING (REGION_ID)
	LEFT JOIN (
		SELECT
			S.REGION_ID,
			COUNT(O.ORDER_ID) AS TOTAL_ORDERS
		FROM
			SALES.ORDERS O
			LEFT JOIN STORES.STORES S USING (STORE_ID)
		GROUP BY
			S.REGION_ID
	) O USING (REGION_ID)

-- ANSWER 20
SELECT
	B.BRAND_ID,
	B.BRAND_NAME,
	P.PRODUCT_COUNT,
	P.AVG_PRODUCT_PRICE,
	OI.TOTAL_REVENUE
FROM
	CORE.DIM_BRAND B
	LEFT JOIN (
		SELECT
			BRAND_ID,
			COUNT(PRODUCT_ID) AS PRODUCT_COUNT,
			ROUND(AVG(PRICE), 2) AS AVG_PRODUCT_PRICE
		FROM
			PRODUCTS.PRODUCTS
		GROUP BY
			BRAND_ID
	) P USING (BRAND_ID)
	LEFT JOIN (
		SELECT
			P.BRAND_ID,
			SUM(OI.NET_AMOUNT) AS TOTAL_REVENUE
		FROM
			SALES.ORDER_ITEMS OI
			LEFT JOIN PRODUCTS.PRODUCTS P ON P.PRODUCT_ID = OI.PROD_ID
		GROUP BY
			BRAND_ID
	) OI USING (BRAND_ID)
ORDER BY
	BRAND_ID

-- ANSWER 21
                    --    CUSTOMERS --> ORDERS
SELECT
	CASE
		WHEN O.CUST_ID IS NULL THEN 'ORPHAN'
		ELSE 'VALID'
	END AS CLASSIFICATION,
	COUNT(*) AS TOTAL
FROM
	CUSTOMERS.CUSTOMERS C
	LEFT JOIN SALES.ORDERS O ON C.CUSTOMER_ID = O.CUST_ID
GROUP BY
	CASE
		WHEN O.CUST_ID IS NULL THEN 'ORPHAN'
		ELSE 'VALID'
	END

                        -- PRODUCTS --> ORDER_ITEMS

SELECT
	CASE
		WHEN OI.PROD_ID IS NULL THEN 'ORPHAN'
		ELSE 'VALID'
	END AS CLASSIFICATION,
	COUNT(*) AS TOTAL
FROM
	PRODUCTS.PRODUCTS P
	LEFT JOIN SALES.ORDER_ITEMS OI ON P.PRODUCT_ID = OI.PROD_ID
GROUP BY
	CASE
		WHEN OI.PROD_ID IS NULL THEN 'ORPHAN'
		ELSE 'VALID'
	END

                        -- EMPLOYEES --> TICKETS

SELECT
	CASE
		WHEN T.AGENT_ID IS NULL THEN 'ORPHAN'
		ELSE 'VALID'
	END AS CLASSIFICATION,
	COUNT(*) AS TOTAL
FROM
	STORES.EMPLOYEES E
	LEFT JOIN SUPPORT.TICKETS T ON E.EMPLOYEE_ID = T.AGENT_ID
GROUP BY
	CASE
		WHEN T.AGENT_ID IS NULL THEN 'ORPHAN'
		ELSE 'VALID'
	END

                    --    ORDERS --> SHIPMENTS

SELECT
	CASE
		WHEN S.ORDER_ID IS NULL THEN 'ORPHAN'
		ELSE 'VALID'
	END AS CLASSIFICATION,
	COUNT(*) AS TOTAL
FROM
	SALES.ORDERS O
	LEFT JOIN SALES.SHIPMENTS S USING (ORDER_ID)
GROUP BY
	CASE
		WHEN S.ORDER_ID IS NULL THEN 'ORPHAN'
		ELSE 'VALID'
	END

-- ANSWER 22
SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	D.DEPT_NAME,
	S.STORE_NAME,
	R.REGION_NAME,
	COUNT(T.TICKET_ID) AS TOTAL_TICKETS,
	COALESCE(
		TO_CHAR(
			AVG(AGE (T.RESOLVED_DATE, T.CREATED_DATE)),
			'DD "days" HH24 "hrs" MI "mins"'
		),
		'No Tickets / Not Resolved'
	) AS AVG_RESOLUTION_TIME
FROM
	STORES.EMPLOYEES E
	LEFT JOIN CORE.DIM_DEPARTMENT D USING (DEPT_ID)
	LEFT JOIN STORES.STORES S USING (STORE_ID)
	LEFT JOIN CORE.DIM_REGION R USING (REGION_ID)
	LEFT JOIN SUPPORT.TICKETS T ON T.AGENT_ID = E.EMPLOYEE_ID
GROUP BY
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	D.DEPT_NAME,
	S.STORE_NAME,
	R.REGION_NAME
ORDER BY
	E.EMPLOYEE_ID

-- ANSWER 23
SELECT
	S.STORE_ID,
	S.STORE_NAME,
	R.REGION_NAME,
	E.EMPLOYEE_COUNT,
	O.ORDER_COUNT,
	O.REVENUE,
	COALESCE(O.AVG_ORDER_VALUE, 0),
	O.RETURN_COUNT,
	O.RETURN_RATE
FROM
	STORES.STORES S
	LEFT JOIN CORE.DIM_REGION R USING (REGION_ID)
	LEFT JOIN (
		SELECT
			STORE_ID,
			COUNT(EMPLOYEE_ID) AS EMPLOYEE_COUNT
		FROM
			STORES.EMPLOYEES
		GROUP BY
			STORE_ID
	) E USING (STORE_ID)
	LEFT JOIN (
		SELECT
			STORE_ID,
			COUNT(ORDER_ID) AS ORDER_COUNT,
			SUM(NET_TOTAL) AS REVENUE,
			AVG(NET_TOTAL) AS AVG_ORDER_VALUE,
			COUNT(
				CASE
					WHEN ORDER_STATUS = 'Returned' THEN 1
					ELSE NULL
				END
			) AS RETURN_COUNT,
			ROUND(
				COUNT(
					CASE
						WHEN ORDER_STATUS = 'Returned' THEN 1
						ELSE NULL
					END
				)::NUMERIC / COUNT(*),
				3
			) AS RETURN_RATE
		FROM
			SALES.ORDERS
		GROUP BY
			STORE_ID
	) O USING (STORE_ID)
ORDER BY
	STORE_ID

-- ANSWER 24
SELECT
	EXTRACT(
		MONTH
		FROM
			ORDER_DATE
	) AS MONTH,
	COUNT(ORDER_ID) AS TOTAL_ORDER,
	SUM(NET_TOTAL) AS REVENUE,
	COUNT(DISTINCT CUST_ID) AS UNIQUE_CUSTOMERS,
	ROUND(AVG(NET_TOTAL), 2) AS AVG_ORDER_VALUE
FROM
	SALES.ORDERS
GROUP BY
	EXTRACT(
		MONTH
		FROM
			ORDER_DATE
	)
ORDER BY
	MONTH

-- ANSWER 25
SELECT
	C.CUSTOMER_ID,
	C.FIRST_NAME,
	C.EMAIL,
	COALESCE(M.TIER_ID, 0) TIER_ID,
	O.ORDER_COUNT,
	O.TOTAL_SPEND,
	O.AVG_ORDER,
	O.LAST_ORDER,
	CURRENT_DATE - O.LAST_ORDER AS RECENCY,
	COALESCE(T.TICKET_COUNT, 0) AS TOTAL_TICKETS,
	CASE
		WHEN O.TOTAL_SPEND > 100000
		AND CURRENT_DATE - O.LAST_ORDER < 10 THEN 'Good'
		WHEN O.TOTAL_SPEND > 50000 THEN 'Average'
		ELSE 'Bad'
	END AS HEALTH
FROM
	CUSTOMERS.CUSTOMERS C
	LEFT JOIN LOYALTY.MEMBERS M USING (CUSTOMER_ID)
	LEFT JOIN (
		SELECT
			CUST_ID,
			COUNT(*) AS ORDER_COUNT,
			SUM(NET_TOTAL) AS TOTAL_SPEND,
			ROUND(AVG(NET_TOTAL), 2) AS AVG_ORDER,
			MAX(ORDER_DATE) AS LAST_ORDER
		FROM
			SALES.ORDERS
		GROUP BY
			CUST_ID
	) O ON C.CUSTOMER_ID = O.CUST_ID
	LEFT JOIN (
		SELECT
			CUSTOMER_ID,
			COUNT(*) AS TICKET_COUNT
		FROM
			SUPPORT.TICKETS
		GROUP BY
			CUSTOMER_ID
	) T USING (CUSTOMER_ID)

-- ANSWER 26
SELECT
	S.STORE_ID,
	S.STORE_NAME,
	R.REGION_NAME,
	S.CITY,
	E.HEADCOUNT,
	E.SALARY_BUDGET,
	O.ORDER_COUNT,
	O.REVENUE,
	O.UNIQUE_CUSTOMER,
	O.RETURN_RATE,
	TIC.TICKET_COUNT
FROM
	STORES.STORES S
	LEFT JOIN CORE.DIM_REGION R USING (REGION_ID)
	LEFT JOIN (
		SELECT
			STORE_ID,
			COUNT(EMPLOYEE_ID) AS HEADCOUNT,
			SUM(SALARY) AS SALARY_BUDGET
		FROM
			STORES.EMPLOYEES
		GROUP BY
			STORE_ID
	) E USING (STORE_ID)
	LEFT JOIN (
		SELECT
			STORE_ID,
			COUNT(ORDER_ID) AS ORDER_COUNT,
			COUNT(DISTINCT CUST_ID) AS UNIQUE_CUSTOMER,
			SUM(NET_TOTAL) AS REVENUE,
			ROUND(AVG(NET_TOTAL), 2) AS AVG_ORDER,
			ROUND(
				COUNT(
					CASE
						WHEN ORDER_STATUS = 'Returned' THEN 1
						ELSE NULL
					END
				)::NUMERIC / COUNT(*),
				3
			) AS RETURN_RATE
		FROM
			SALES.ORDERS
		GROUP BY
			STORE_ID
	) O USING (STORE_ID)
	LEFT JOIN (
		SELECT
			E.STORE_ID,
			COUNT(*) AS TICKET_COUNT
		FROM
			SUPPORT.TICKETS T
			LEFT JOIN STORES.EMPLOYEES E ON E.EMPLOYEE_ID = T.AGENT_ID
		GROUP BY
			E.STORE_ID
	) TIC USING (STORE_ID)        

-- ANSWER 27
SELECT
	*
FROM
	SALES.ORDERS O
	INNER JOIN SALES.ORDER_ITEMS OI USING (ORDER_ID)
	INNER JOIN PRODUCTS.PRODUCTS P ON P.PRODUCT_ID = OI.PROD_ID
	-- total rows 375202
	-- returns only matching records across all tables
	-- rows exist only where order_id and product_id are valid in all tables
	-- no NULL values in joined columns
	-- skips any unmatched (orphan) records
	-- row count = only valid relationships

	
SELECT
	*
FROM
	SALES.ORDERS O
	LEFT JOIN SALES.ORDER_ITEMS OI USING (ORDER_ID)
	LEFT JOIN PRODUCTS.PRODUCTS P ON P.PRODUCT_ID = OI.PROD_ID
	-- total rows 375202
	-- returns all orders (left table is fully preserved)
	-- if order has no order_items → oi columns = NULL
	-- if order_item has no valid product → product columns = NULL
	-- unmatched rows are NOT removed (only left side guaranteed)
	-- row count = at least number of orders (can increase due to 1:N)

	
SELECT
	*
FROM
	SALES.ORDERS O
	FULL JOIN SALES.ORDER_ITEMS OI USING (ORDER_ID)
	FULL JOIN PRODUCTS.PRODUCTS P ON P.PRODUCT_ID = OI.PROD_ID
	-- total rows 375806 (more, because there are some preoducs that are never ordered)
	-- returns all records from all tables (orders + order_items + products)
	-- unmatched rows from any table are included with NULLs
	-- helps identify:
	--   - orders without items
	--   - order_items without orders
	--   - order_items with invalid products
	--   - products never ordered
	-- row count = highest (includes all matches + all mismatches)

-- ANSWER 28
-- CUSTOMERS --> ORDERS
SELECT
	CASE
		WHEN O.CUST_ID IS NOT NULL
		AND C.CUSTOMER_ID IS NOT NULL THEN 'Good Records'
		WHEN C.CUSTOMER_ID IS NULL THEN 'Orphan Order'
		ELSE 'ORPHAN CUSTOMER'
	END AS STATUS,
	COUNT(*)
FROM
	CUSTOMERS.CUSTOMERS C
	FULL JOIN SALES.ORDERS O ON O.CUST_ID = C.CUSTOMER_ID
GROUP BY
	CASE
		WHEN O.CUST_ID IS NOT NULL
		AND C.CUSTOMER_ID IS NOT NULL THEN 'Good Records'
		WHEN C.CUSTOMER_ID IS NULL THEN 'Orphan Order'
		ELSE 'ORPHAN CUSTOMER'
	END

EMPLOYEES --> TICKETS
SELECT
	CASE
		WHEN E.EMPLOYEE_ID IS NOT NULL
		AND T.AGENT_ID IS NOT NULL THEN 'Good Records'
		WHEN T.AGENT_ID IS NULL THEN 'Orphan EMPLOYEES'
		ELSE 'ORPHAN TICKETS'
	END AS STATUS,
	COUNT(*)
FROM
	STORES.EMPLOYEES E
	FULL JOIN SUPPORT.TICKETS T ON E.EMPLOYEE_ID = T.AGENT_ID
GROUP BY
	CASE
		WHEN E.EMPLOYEE_ID IS NOT NULL
		AND T.AGENT_ID IS NOT NULL THEN 'Good Records'
		WHEN T.AGENT_ID IS NULL THEN 'Orphan EMPLOYEES'
		ELSE 'ORPHAN TICKETS'
	END

-- sales.orders.order_id -> sales.shipments.order_id
SELECT
	CASE
		WHEN S.ORDER_ID IS NULL THEN 'Not Shipped'
		WHEN O.ORDER_ID IS NULL THEN 'Orphan Shipment'
		ELSE 'Delivered/Shipped/Returned'
	END AS STATUS,
	COUNT(*)
FROM
	SALES.ORDERS O
	FULL JOIN SALES.SHIPMENTS S ON S.ORDER_ID = O.ORDER_ID
GROUP BY
	CASE
		WHEN S.ORDER_ID IS NULL THEN 'Not Shipped'
		WHEN O.ORDER_ID IS NULL THEN 'Orphan Shipment'
		ELSE 'Delivered/Shipped/Returned'
	END

-- products.products.product_id -> sales.order_items.prod_id
SELECT
	CASE
		WHEN OI.PROD_ID IS NULL THEN 'Never Ordered Product'
		WHEN P.PRODUCT_ID IS NULL THEN 'Orphan Order Item'
		ELSE 'Good Records'
	END AS STATUS,
	COUNT(*)
FROM
	PRODUCTS.PRODUCTS P
	FULL JOIN SALES.ORDER_ITEMS OI ON OI.PROD_ID = P.PRODUCT_ID
GROUP BY
	CASE
		WHEN OI.PROD_ID IS NULL THEN 'Never Ordered Product'
		WHEN P.PRODUCT_ID IS NULL THEN 'Orphan Order Item'
		ELSE 'Good Records'
	END