-- ANSWER 4

CREATE TABLE DAY_4.MOVIE_REVIEWS (

REVIEW ID SERIAL PRIMARY KEY,

MOVIE NAME VARCHAR (20) NOT NULL,

REVIEWER NAME VARCHAR (20) NOT NULL,

RATING INT NOT NULL CHECK (RATING BETWEEN 1 AND 10),

REVIEW STATUS VARCHAR(20) DEFAULT 'PENDING CHECK (REVIEW STATUS IN ('PENDING', 'APPROVED', 'REJECTED')) );

-- ANSWER 5

INSERT INTO DAY_4.MOVIE_REVIEWS (MOVIE_NAME, REVIEWER_NAME, RATING, REVIEW_STATUS )

VALUES ('GOT', 'PIYUSH RAI', 9, 'APPROVED');

-- ANSWER 6

INSERT INTO DAY_4.MOVIE_REVIEWS (MOVIE_NAME, REVIEWER_NAME, RATING, REVIEW_STATUS) VALUES ('STRANGER THINGS', 'SOURAV', 15, 'APPROVED');

INSERT INTO DAY_4.MOVIE_REVIEWS (MOVIE_NAME, REVIEWER_NAME, RATING)

VALUES ('BREAKING BAD', 'SURAJ',8);

SELECT * FROM DAY_4.MOVIE_REVIEWS;

-- ANSWER 9,10 AND 11

CREATE TABLE DAY 4.DEPARTMENTS (

DEPT_ID SERIAL PRIMARY KEY,

DEPT_NAME VARCHAR (20) UNIQUE NOT NULL

);

CREATE TABLE DAY_4.STAFF(

STAFF ID SERIAL PRIMARY KEY,

STAFF NAME VARCHAR (20) NOT NULL,

DEPT_ID INT NOT NULL,

CONSTRAINT FK_DEPARTMENT FOREIGN KEY (DEPT_ID) REFERENCES DAY_4.DEPARTMENTS (DEPT_ID)

);

INSERT INTO DAY_4.DEPARTMENTS (DEPT_NAME) VALUES ('Engineering');

INSERT INTO DAY_4.STAFF (STAFF_NAME, DEPT_ID) VALUES ('PIYUSH RAI', 1);

INSERT INTO DAY_4.STAFF (STAFF_NAME, DEPT_ID) VALUES ('RAHUL',999);

-- ANSWER 12,13 AND 14

CREATE TABLE DAY_4.PROJECTS(

); PROJECT_ID SERIAL PRIMARY KEY, PROJECT_NAME VARCHAR (30) NOT NULL

CREATE TABLE DAY_4.TASKS (

TASK_ID SERIAL PRIMARY KEY,

PROJECT_ID INT NOT NULL,

TASK NAME VARCHAR (30) NOT NULL,

CONSTRAINT FK_PROJECT

FOREIGN KEY (PROJECT_ID)

REFERENCES DAY_4.PROJECTS (PROJECT_ID) ON DELETE CASCADE

);

INSERT INTO DAY_4.PROJECTS (PROJECT_NAME) VALUES ('FRONTEND DEV');

INSERT INTO DAY_4. TASKS (PROJECT_ID, TASK_NAME) VALUES (1, 'DESIGN UI'), (1, 'DEVELOP FRONTEND'), (1, 'TESTING');

DELETE FROM DAY_4.PROJECTS
WHERE PROJECT_ID = 1;

-- ANSWER 16,17,18 AND 19

CREATE SCHEMA IF NOT EXISTS HR;								
								
CREATE TABLE HR.DEPARTMENTS(								
	DEPT_ID SERIAL PRIMARY KEY,							
	DEPT_NAME VARCHAR(50) UNIQUE NOT NULL,							
	CREATED_AT TIMESTAMPTZ DEFAULT NOW()							
);								
								
CREATE TABLE HR.EMPLOYEES(								
	EMP_ID SERIAL PRIMARY KEY,							
	EMP_NAME VARCHAR(100) NOT NULL,							
	EMAIL VARCHAR(150) UNIQUE NOT NULL,							
	SALARY NUMERIC(12,2) NOT NULL CHECK (SALARY >0),							
	EMP_TYPE VARCHAR(20) NOT NULL DEFAULT 'FULL TIME'							
	CHECK (EMP_TYPE IN ('FULL TIME','PART TIME','CONTRACT','INTERN')),							
	DEPT_ID INT NOT NULL,							
	HIRE_DATE DATE NOT NULL DEFAULT CURRENT_DATE,							
	CONSTRAINT FK_DEPARTMENT							
		FOREIGN KEY (DEPT_ID)						
		REFERENCES HR.DEPARTMENTS(DEPT_ID)						
		ON DELETE CASCADE						
);	

CREATE TABLE HR.ATTENDANCE(									
	EMP_ID INT NOT NULL,								
	ATT_DATE DATE NOT NULL,								
	STATUS VARCHAR(10) NOT NULL DEFAULT 'PRESENT'								
		CHECK(STATUS IN ('PRESENT','ABSENT','HALF DAY','LEAVE')),							
	PRIMARY KEY(EMP_ID,ATT_DATE),								
									
	CONSTRAINT FK_EMPLOYEE								
	FOREIGN KEY (EMP_ID)								
	REFERENCES HR.EMPLOYEES(EMP_ID)								
	ON DELETE CASCADE								
);									

-- ANSWER 20-27

INSERT INTO HR.DEPARTMENTS (DEPT_NAME) VALUES ('ENGINEERING'),('MARKETING');									
									
INSERT INTO HR.EMPLOYEES (EMP_NAME,EMAIL,SALARY,EMP_TYPE,DEPT_ID)									
VALUES ('PIYUSH RAI','piyush@gmail.com',60000,'FULL TIME',1),									
	   ('SOURAV','sourav@gmail.com',45000,'PART TIME',2),								
	   ('AMAN','aman@gmail.com',15000,'INTERN',1);								
									
INSERT INTO HR.EMPLOYEES (EMAIL,SALARY,EMP_TYPE,DEPT_ID)									
VALUES ('anish@gmail.com',30000,'FULL TIME',1);									
									
INSERT INTO HR.EMPLOYEES (EMP_NAME,EMAIL,SALARY,EMP_TYPE,DEPT_ID)									
VALUES ('TEST USER','test@gmail.com',-20000,'FULL TIME',1);									
									
INSERT INTO HR.EMPLOYEES (EMP_NAME,EMAIL,SALARY,EMP_TYPE,DEPT_ID)									
VALUES ('DUPLICATE USER','piyush@gmail.com',20000,'FULL TIME',1);									
									
INSERT INTO HR.EMPLOYEES (EMP_NAME,EMAIL,SALARY,EMP_TYPE,DEPT_ID)									
VALUES ('foreign USER','foreign@gmail.com',20000,'FULL TIME',999);

DELETE FROM HR.DEPARTMENTS WHERE DEPT_ID = 1;						
						
INSERT INTO HR.ATTENDANCE(EMP_ID,ATT_DATE,STATUS)						
VALUES (1,CURRENT_DATE,'PRESENT'),						
	   (1,CURRENT_DATE - INTERVAL '1 DAY','ABSENT');					
						
DELETE FROM HR.EMPLOYEES WHERE EMP_ID =1;						
						
SELECT * FROM HR.ATTENDANCE WHERE EMP_ID = 1;						

-- ANSWER 28 AND 29

CREATE TABLE DEMO_PARENT(						
	ID SERIAL PRIMARY KEY,					
	NAME TEXT					
);						
						
CREATE TABLE DEMO_CHILD_CASCADE(						
	ID SERIAL PRIMARY KEY,					
	PARENT_ID INT REFERENCES DEMO_PARENT(ID)					
	ON DELETE CASCADE					
);						
						
CREATE TABLE DEMO_CHILD_RESTRICT(						
	ID SERIAL PRIMARY KEY,					
	PARENT_ID INT REFERENCES DEMO_PARENT(ID)					
	ON DELETE CASCADE					
);						
						
INSERT INTO DEMO_PARENT(NAME) VALUES ('PARENT 1');						
INSERT INTO DEMO_CHILD_CASCADE (PARENT_ID) VALUES (1);						
INSERT INTO DEMO_CHILD_RESTRICT (PARENT_ID) VALUES (1);						
--TRY DELETING PARENT						
DELETE FROM DEMO_PARENT WHERE ID = 1;						
--REMOVE RESTRICT CHILD AND RETRY						
DELETE FROM DEMO_CHILD_RESTRICT WHERE PARENT_ID = 1;						
DELETE FROM DEMO_PARENT WHERE ID = 1;						


