-- ANSWER 5
				-- METHOD 1																	
SELECT DATE_PART('YEAR',CURRENT_DATE)- DATE_PART('YEAR',DATE '1999-11-11') AS AGE;											
											
				-- METHOD 2	PostgreSQL(SPECIFIC)																
SELECT EXTRACT(YEAR FROM AGE(CURRENT_DATE,DATE '1999-11-11')) AS AGE;											

-- ANSWER 11,12 AND 13
CREATE SCHEMA IF NOT EXISTS FOOD_DELIVERY;										
										
SET SEARCH_PATH TO FOOD_DELIVERY;										
										
CREATE TABLE RESTAURANTS(										
	RESTAURANT_ID UUID PRIMARY KEY default gen_random_uuid(),									
	NAME VARCHAR(150) NOT NULL,									
	PHONE VARCHAR(20) NOT NULL CHECK (PHONE LIKE '+91%'),									
	IS_VEG_ONLY BOOLEAN NOT NULL,									
	AVG_COST_FOR_TWO NUMERIC(10,2) NOT NULL CHECK (AVG_COST_FOR_TWO >= 0),									
	CUISINE_TAGS TEXT[],									
	CREATED_AT TIMESTAMPTZ DEFAULT NOW()									
);										
										
INSERT INTO RESTAURANTS(NAME,PHONE,IS_VEG_ONLY,AVG_COST_FOR_TWO,CUISINE_TAGS)										
VALUES (										
	'PIYUSH RAI','+91353626736',TRUE,500.00,ARRAY['CHINESE','ITALIAN']									
),										
(										
	'PIZZA','+917267267828',FALSE,300,ARRAY['INDIAN','SPANISH']									
);		

