CREATE TABLE ORDER_TRACKING(
	TRACKING_ID SERIAL,
	ORDER_ID INT NOT NULL,
	STATUS VARCHAR(20) NOT NULL CHECK(STATUS IN ('PENDING','SHIPPED','DELIVERED','CANCELLED','COMPLETED','REFUNDED')),
	RATING INT CHECK (RATING BETWEEN 1 AND 5 )
);

INSERT INTO ORDER_TRACKING(ORDER_ID,STATUS,RATING) VALUES (1,'PENDING',5);