CREATE TABLE ORDERS (
	ORDER_ID SERIAL,
	CUSTOMER_NAME VARCHAR(50) NOT NULL,
	ORDER_STATUS VARCHAR(20) DEFAULT 'pending',
	CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO
	ORDERS (CUSTOMER_NAME)
VALUES
	('Piyush')
INSERT INTO
	ORDERS (CUSTOMER_NAME, ORDER_STATUS, CREATED_AT)
VALUES
	('ROHAN', NULL, NULL)
SELECT
	*
FROM
	ORDERS