CREATE TABLE PRODUCTS (
	PRODUCT_ID TEXT,
	PRODUCT_NAME TEXT,
	PRICE TEXT,
	IN_STOCK TEXT
);

CREATE TABLE PRODUCTS.PRODUCTS (
	PRODUCT_ID TEXT,
	PRODUCT_NAME TEXT,
	PRICE TEXT,
	IN_STOCK TEXT
);

CREATE SCHEMA DAY_02;

CREATE TABLE DAY_02.STUDENTS (
	STUDENT_ID TEXT,
	STUDENT_NAME TEXT,
	EMAIL TEXT,
	AGE TEXT,
	PHONE_NO TEXT,
	ENROLLED_TO TEXT
);

ALTER TABLE DAY_02.STUDENTS
ADD COLUMN GENDER TEXT;

ALTER TABLE DAY_02.STUDENTS
RENAME COLUMN ENROLLED_TO TO REGISTRATION_DATE;

ALTER TABLE DAY_02.STUDENTS
ALTER COLUMN AGE TYPE INT USING AGE::INTEGER;

SELECT
	*
FROM
	DAY_02.STUDENTS;