-- ANSWER 1
SELECT
	O.ORDER_ID,
	O.ORDER_DATE,
	P.PAYMENT_MODE,
	P.AMOUNT
FROM
	SALES.ORDERS O
	JOIN SALES.PAYMENTS P USING (ORDER_ID);

SELECT
	O.ORDER_ID,
	O.ORDER_DATE,
	P.PAYMENT_MODE,
	P.AMOUNT
FROM
	SALES.ORDERS O
	JOIN SALES.PAYMENTS P USING (ORDER_ID);

-- ANSWER 2
SELECT
	P.PRODUCT_NAME,
	B.BRAND_NAME,
	P.PRICE
FROM
	PRODUCTS.PRODUCTS P
	JOIN CORE.DIM_BRAND B USING (BRAND_ID);

-- ANSWER 3
SELECT
	E.FIRST_NAME || ' ' || E.LAST_NAME AS CUSTOMER_NAME,
	E.ROLE,
	S.STORE_NAME,
	S.CITY
FROM
	STORES.EMPLOYEES E
	JOIN STORES.STORES S USING (STORE_ID);

-- ANSWER 4
SELECT
	P.PRODUCT_NAME,
	OI.QUANTITY,
	O.NET_TOTAL
FROM
	SALES.ORDERS O
	JOIN SALES.ORDER_ITEMS OI USING (ORDER_ID)
	JOIN PRODUCTS.PRODUCTS P ON OI.PROD_ID = P.PRODUCT_ID
ORDER BY
	O.NET_TOTAL DESC
LIMIT
	10;

-- ANSWER 5
SELECT
	S.STORE_ID,
	COUNT(*) AS TOTAL_STORES
FROM
	STORES.STORES S
	LEFT JOIN SALES.ORDERS O USING (STORE_ID)
GROUP BY
	S.STORE_ID;

-- ANSWER 6
SELECT
	S.STORE_ID,
	COUNT(*) AS TOTAL_STORES
FROM
	STORES.STORES S
	LEFT JOIN SALES.ORDERS O USING (STORE_ID)
WHERE
	O.STORE_ID IS NULL
GROUP BY
	S.STORE_ID;

-- ANSWER 7
SELECT
	P.PRODUCT_NAME,
	S.SUPPLIER_NAME
FROM
	PRODUCTS.PRODUCTS P
	LEFT JOIN PRODUCTS.SUPPLIERS S USING (SUPPLIER_ID);

-- ANSWER 8
SELECT
	E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLOYEE_NAME,
	COUNT(T.TICKET_ID) AS TOTAL_TICKET_HANDLED
FROM
	STORES.EMPLOYEES E
	LEFT JOIN SUPPORT.TICKETS T ON E.EMPLOYEE_ID = T.AGENT_ID
GROUP BY
	FIRST_NAME,
	LAST_NAME;

-- ANSWER 9
-- RIGHT JOIN
SELECT
	E.FIRST_NAME,
	D.DEPT_NAME
FROM
	STORES.EMPLOYEES E
	RIGHT JOIN CORE.DIM_DEPARTMENT D USING (DEPT_ID);

-- LEFT JOIN
SELECT
	E.FIRST_NAME,
	D.DEPT_NAME
FROM
	CORE.DIM_DEPARTMENT D
	RIGHT JOIN STORES.EMPLOYEES E USING (DEPT_ID);

-- ANSWER 10
SELECT
	C.CATEGORY_NAME,
	E.AMOUNT
FROM
	FINANCE.EXPENSES E
	RIGHT JOIN CORE.DIM_EXPENSE_CATEGORY C USING (EXP_CAT_ID);

-- ANSWER 11
SELECT
	E.FIRST_NAME,
	D.DEPT_NAME
FROM
	STORES.EMPLOYEES E
	RIGHT JOIN CORE.DIM_DEPARTMENT D USING (DEPT_ID)
WHERE
	E.DEPT_ID IS NULL;

-- ANSWER 12
SELECT
	P.PAYMENT_ID,
	P.PAYMENT_MODE,
	C.FIRST_NAME || ' ' || C.LAST_NAME AS CUSTOMER_NAME,
	O.ORDER_DATE
FROM
	SALES.PAYMENTS P
	JOIN SALES.ORDERS O USING (ORDER_ID)
	JOIN CUSTOMERS.CUSTOMERS C ON O.CUST_ID = C.CUSTOMER_ID
	-- ANSWER 13
SELECT
	R.REVIEW_ID,
	C.FIRST_NAME || ' ' || C.LAST_NAME AS CUSTOMER_NAME,
	P.PRODUCT_NAME,
	B.BRAND_NAME
FROM
	CUSTOMERS.REVIEWS R
	INNER JOIN CUSTOMERS.CUSTOMERS C USING (CUSTOMER_ID)
	INNER JOIN PRODUCTS.PRODUCTS P USING (PRODUCT_ID)
	INNER JOIN CORE.DIM_BRAND B USING (BRAND_ID)
ORDER BY
	REVIEW_ID;

-- ANSWER 14
SELECT
	S.STORE_ID,
	S.STORE_NAME,
	D.REGION_NAME,
	D.STATE,
	COUNT(DISTINCT E.EMPLOYEE_ID) AS TOTAL_EMPLOYEE,
	COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS
FROM
	STORES.STORES S
	LEFT JOIN CORE.DIM_REGION D USING (REGION_ID)
	LEFT JOIN STORES.EMPLOYEES E USING (STORE_ID)
	LEFT JOIN SALES.ORDERS O USING (STORE_ID)
GROUP BY
	S.STORE_ID,
	S.STORE_NAME,
	D.REGION_NAME,
	D.STATE;

-- ANSWER 15
SELECT
	* DC.CATEGORY_ID,
	DC.CATEGORY_NAME,
	COUNT(DISTINCT P.PRODUCT_ID) AS TOTAL_PRODUCT,
	SUM(OI.QUANTITY) AS TOTAL_QTY_SOLD,
	SUM(OI.NET_AMOUNT) AS TOTAL_REVENUE
FROM
	CORE.DIM_CATEGORY DC
	JOIN CORE.DIM_BRAND DB USING (CATEGORY_ID)
	JOIN PRODUCTS.PRODUCTS P USING (BRAND_ID)
	JOIN SALES.ORDER_ITEMS OI ON P.PRODUCT_ID = OI.PROD_ID
GROUP BY
	DC.CATEGORY_ID,
	DC.CATEGORY_NAME;

-- ANSWER 16
-- WITHIN ON CLAUSE
SELECT
	S.STORE_ID,
	COUNT(*) AS TOTAL_STORES
FROM
	STORES.STORES S
	LEFT JOIN SALES.ORDERS O ON S.STORE_ID = O.STORE_ID
	AND O.ORDER_STATUS = 'Delivered'
GROUP BY
	S.STORE_ID;

-- USING WHERE
SELECT
	S.STORE_ID,
	COUNT(*) AS TOTAL_STORES
FROM
	STORES.STORES S
	LEFT JOIN SALES.ORDERS O ON S.STORE_ID = O.STORE_ID
WHERE
	O.ORDER_STATUS = 'Delivered'
GROUP BY
	S.STORE_ID;

-- ANSWER 17
SELECT
	O.ORDER_ID,
	COUNT(R.RETURN_ID) AS LATE_RETURNS
FROM
	SALES.ORDERS O
	LEFT JOIN SALES.RETURNS R ON O.ORDER_ID = R.ORDER_ID
	AND R.RETURN_DATE > O.ORDER_DATE --NON-EQUI CONDITION
GROUP BY
	O.ORDER_ID;

-- ANSWER 18
SELECT
	C.CUSTOMER_ID,
	C.FIRST_NAME || ' ' || C.LAST_NAME AS CUSTOMER_NAME,
	COUNT(P.PAYMENT_ID) AS FAST_PAYMENTS_7DAYS
FROM
	CUSTOMERS.CUSTOMERS C
	LEFT JOIN SALES.ORDERS O ON C.CUSTOMER_ID = O.CUST_ID
	LEFT JOIN SALES.PAYMENTS P ON P.ORDER_ID = O.ORDER_ID
	AND P.PAYMENT_DATE >= O.ORDER_DATE
	AND P.PAYMENT_DATE <= O.ORDER_DATE + INTERVAL '7 days'
GROUP BY
	C.CUSTOMER_ID,
	C.FIRST_NAME,
	C.LAST_NAME;

-- ANSWER 19
SELECT
	C.FIRST_NAME || ' ' || C.LAST_NAME AS CUSTOMER_NAME,
	O.ORDER_DATE,
	O.NET_TOTAL
FROM
	SALES.ORDERS O
	JOIN CUSTOMERS.CUSTOMERS C ON O.CUST_ID = C.CUSTOMER_ID
ORDER BY
	O.ORDER_DATE
LIMIT
	20;

-- ANSWER 19