-- ANSWER 1
SELECT
	*
FROM
	STORES.STORES S1
	JOIN STORES.STORES S2 ON S1.REGION_ID = S2.REGION_ID
	AND S1.STORE_ID < S2.STORE_ID

-- ANSWER 2
SELECT
	E1.FIRST_NAME AS FIRST_EMP,
	E1.SALARY AS E1_SALARY,
	E2.FIRST_NAME AS SECOND_EMP,
	E2.SALARY AS E2_SALARY,
	ABS(E1.SALARY - E2.SALARY) AS GAP
FROM
	STORES.EMPLOYEES E1
	JOIN STORES.EMPLOYEES E2 ON E1.STORE_ID = E2.STORE_ID
	AND E1.EMPLOYEE_ID < E2.EMPLOYEE_ID
	AND ABS(E1.SALARY - E2.SALARY) <= 5000

-- ANSWER 3
SELECT
	E1.DEPT_ID,
	COUNT(*) AS PAIR_COUNT
FROM
	STORES.EMPLOYEES E1
	JOIN STORES.EMPLOYEES E2 ON E1.DEPT_ID = E2.DEPT_ID
	AND E1.EMPLOYEE_ID < E2.EMPLOYEE_ID
WHERE
	ABS(E1.SALARY - E2.SALARY) > 100000
GROUP BY
	E1.DEPT_ID
ORDER BY
	E1.DEPT_ID

-- ANSWER 4
SELECT
	T.TIER_ID,
	T.TIER_NAME,
	MP.MARKETING_PLATFORM
FROM
	LOYALTY.TIERS T
	CROSS JOIN (
		SELECT
			UNNEST(
				ARRAY['Email', 'Website', 'Instagram', 'Facebook']
			) AS MARKETING_PLATFORM
	) MP

-- ANSWER 5
SELECT
	R.REGION_ID,
	R.REGION_NAME
FROM
	CORE.DIM_REGION R
	CROSS JOIN (
		SELECT DISTINCT
			REGION_ID
		FROM
			CORE.DIM_REGION
	) R2
	LEFT JOIN STORES.STORES S ON R.REGION_ID = S.REGION_ID
WHERE
	S.REGION_ID IS NULL;

-- ANSWER 6
SELECT
	STORE_ID,
	STORE_NAME,
	'Q' || QUARTERS || '-2025' AS QUARTERLY
FROM
	STORES.STORES
	CROSS JOIN (
		SELECT
			GENERATE_SERIES(1, 4) AS QUARTERS
	)

-- ANSWER 7
SELECT
	CITY
FROM
	STORES.STORES
UNION
SELECT
	CITY
FROM
	CUSTOMERS.ADDRESSES

-- ANSWER 8
SELECT
	PAYMENT_DATE,
	AMOUNT,
	'PAYMENT' AS SOURCE
FROM
	SALES.PAYMENTS
UNION ALL
SELECT
	RETURN_DATE,
	REFUND_AMOUNT,
	'REFUND' AS SOURCE
FROM
	SALES.RETURNS

-- ANSWER 9
                              -- WITH UNION  (REMOVES DUPLICATES)

SELECT
	COUNT(*)
FROM
	(
		SELECT
			EMAIL
		FROM
			CUSTOMERS.CUSTOMERS
		UNION
		SELECT
			EMAIL
		FROM
			STORES.EMPLOYEES
	)

                             -- WITH UNION ALL (KEEP DUPLICATES)
SELECT
	COUNT(*)
FROM
	(
		SELECT
			EMAIL
		FROM
			CUSTOMERS.CUSTOMERS
		UNION ALL
		SELECT
			EMAIL
		FROM
			STORES.EMPLOYEES
	)                             

-- ANSWER 10
SELECT
	ROLE
FROM
	STORES.EMPLOYEES
WHERE
	DEPT_ID = 1
INTERSECT
SELECT
	ROLE
FROM
	STORES.EMPLOYEES
WHERE
	DEPT_ID = 3;

-- ANSWER 11
SELECT DISTINCT
	CUST_ID
FROM
	SALES.ORDERS
WHERE
	ORDER_ID IS NOT NULL
INTERSECT
SELECT DISTINCT
	CUSTOMER_ID
FROM
	LOYALTY.MEMBERS

-- ANSWER 12
SELECT
	DATE_TRUNC('Month', ORDER_DATE)
FROM
	SALES.ORDERS
WHERE
	ORDER_DATE >= '2025-01-01'
	AND ORDER_DATE < '2026-01-01'
INTERSECT
SELECT
	DATE_TRUNC('Month', RETURN_DATE)
FROM
	SALES.RETURNS
WHERE
	RETURN_DATE >= '2025-01-01'
	AND RETURN_DATE < '2026-01-01'

-- ANSWER 13
SELECT
	ROLE
FROM
	STORES.EMPLOYEES
WHERE
	DEPT_ID = 1
EXCEPT
SELECT
	ROLE
FROM
	STORES.EMPLOYEES
WHERE
	DEPT_ID = 5;

-- ANSWER 14
SELECT
	CUSTOMER_ID
FROM
	LOYALTY.MEMBERS
EXCEPT
SELECT
	CUST_ID
FROM
	SALES.ORDERS

-- ANSWER 15
-- city with stores but not customers
SELECT
	CITY
FROM
	STORES.STORES
EXCEPT
SELECT
	CITY
FROM
	CUSTOMERS.ADDRESSES

	
	-- city with customers but no stores 
SELECT
	CITY
FROM
	CUSTOMERS.ADDRESSES
EXCEPT
SELECT
	CITY
FROM
	STORES.STORES

-- ANSWER 16
SELECT
	O.ORDER_DATE,
	'ORDER' AS TYPE,
	C.FIRST_NAME AS CUSTOMER,
	O.NET_TOTAL AS AMOUNT
FROM
	SALES.ORDERS O
	JOIN CUSTOMERS.CUSTOMERS C ON O.CUST_ID = C.CUSTOMER_ID
UNION ALL
SELECT
	O.ORDER_DATE,
	'PAYMENT' AS TYPE,
	C.FIRST_NAME AS CUSTOMER,
	P.AMOUNT AS AMOUNT
FROM
	SALES.ORDERS O
	JOIN SALES.PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
	JOIN CUSTOMERS.CUSTOMERS C ON O.CUST_ID = C.CUSTOMER_ID
UNION ALL
SELECT
	R.RETURN_DATE,
	'RETURN' AS TYPE,
	C.FIRST_NAME AS CUSTOMER,
	R.REFUND_AMOUNT AS AMOUNT
FROM
	SALES.RETURNS R
	JOIN PRODUCTS.PRODUCTS P ON P.PRODUCT_ID = R.PROD_ID
	JOIN SALES.ORDERS O USING (ORDER_ID)
	JOIN CUSTOMERS.CUSTOMERS C ON O.CUST_ID = C.CUSTOMER_ID

-- ANSWER 17
SELECT
	BRAND_ID
FROM
	CORE.DIM_BRAND
INTERSECT
SELECT
	P.BRAND_ID
FROM
	SALES.ORDER_ITEMS OI
	LEFT JOIN PRODUCTS.PRODUCTS P ON P.PRODUCT_ID = OI.PROD_ID
EXCEPT
SELECT
	P.BRAND_ID
FROM
	SALES.RETURNS R
	LEFT JOIN PRODUCTS.PRODUCTS P ON P.PRODUCT_ID = R.PROD_ID

-- ANSWER 18
SELECT
	DATE_TRUNC('quarter', ORDER_DATE) AS QUARTER,
	'Sales' AS DEPARTMENT,
	'Order' AS METRIC,
	COUNT(DISTINCT ORDER_ID) AS VALUE
FROM
	SALES.ORDERS
GROUP BY
	DATE_TRUNC('quarter', ORDER_DATE)
UNION ALL
SELECT
	DATE_TRUNC('quarter', ORDER_DATE) AS QUARTER,
	'Sales' AS DEPARTMENT,
	'Revenue' AS METRIC,
	SUM(NET_TOTAL) AS VALUE
FROM
	SALES.ORDERS
GROUP BY
	DATE_TRUNC('quarter', ORDER_DATE)
UNION ALL
SELECT
	DATE_TRUNC('quarter', CREATED_DATE) AS QUARTER,
	'Support' AS DEPARTMENT,
	'Tickets' AS METRIC,
	COUNT(DISTINCT TICKET_ID) AS VALUE
FROM
	SUPPORT.TICKETS
GROUP BY
	DATE_TRUNC('quarter', CREATED_DATE)
UNION ALL
SELECT
	DATE_TRUNC('quarter', CREATED_DATE) AS QUARTER,
	'Support' AS DEPARTMENT,
	'Resolution Rate' AS METRIC,
	ROUND(
		COUNT(
			CASE
				WHEN STATUS = 'Resolved' THEN 1
			END
		)::NUMERIC / COUNT(DISTINCT TICKET_ID),
		2
	) AS VALUE
FROM
	SUPPORT.TICKETS
GROUP BY
	DATE_TRUNC('quarter', CREATED_DATE)
UNION ALL
SELECT
	DATE_TRUNC('quarter', START_DATE) AS QUARTER,
	'Marketing' AS DEPARTMENT,
	'Campaigns' AS METRIC,
	COUNT(CAMPAIGN_ID) AS VALUE
FROM
	MARKETING.CAMPAIGNS
GROUP BY
	DATE_TRUNC('quarter', START_DATE)
UNION ALL
SELECT
	DATE_TRUNC('quarter', SPEND_DATE) AS QUARTER,
	'Marketing' AS DEPARTMENT,
	'Spend' AS METRIC,
	SUM(AMOUNT) AS VALUE
FROM
	MARKETING.ADS_SPEND
GROUP BY
	DATE_TRUNC('quarter', SPEND_DATE)
ORDER BY
	QUARTER,
	DEPARTMENT,
	METRIC

-- ANSWER 19
SELECT
	S1.STORE_ID AS STORE1,
	S2.STORE_ID AS STORE2,
	S1.CITY
FROM
	STORES.STORES S1
	JOIN STORES.STORES S2 ON S1.CITY = S1.CITY
	AND S1.STORE_ID < S2.STORE_ID

-- ANSWER 20
SELECT
	E1.FIRST_NAME || ' ' || E1.LAST_NAME AS EMPLOYEE1,
	E2.FIRST_NAME || ' ' || E2.LAST_NAME AS EMPLOYEE2,
	E1.ROLE,
	E1.STORE_ID
FROM
	STORES.EMPLOYEES E1
	JOIN STORES.EMPLOYEES E2 ON E1.ROLE = E2.ROLE
	AND E1.STORE_ID = E2.STORE_ID
	AND E1.EMPLOYEE_ID < E2.EMPLOYEE_ID

-- ANSWER 21
SELECT
	'customer' AS SOURCE,
	EMAIL
FROM
	CUSTOMERS.CUSTOMERS
UNION
SELECT
	'employee' AS SOURCE,
	EMAIL
FROM
	STORES.EMPLOYEES

-- ANSWER 22
SELECT
	PRODUCT_ID
FROM
	PRODUCTS.PRODUCTS
EXCEPT
SELECT
	PROD_ID
FROM
	SALES.ORDER_ITEMS

-- ANSWER 23
SELECT
	E1.FIRST_NAME AS EMP1,
	E1.SALARY AS SAL_EMP1,
	E2.FIRST_NAME AS EMP2,
	E2.SALARY AS SAL_EMP2
FROM
	STORES.EMPLOYEES E1
	JOIN STORES.EMPLOYEES E2 ON E2.DEPT_ID = E1.DEPT_ID
	AND E2.EMPLOYEE_ID < E1.EMPLOYEE_ID
WHERE
	ABS(E1.SALARY - E2.SALARY) <= 1000

-- ANSWER 24
SELECT
	D.DEPT_NAME,
	ROLES.ROLE
FROM
	CORE.DIM_DEPARTMENT D
	CROSS JOIN (
		SELECT DISTINCT
			ROLE
		FROM
			STORES.EMPLOYEES
	) ROLES
	LEFT JOIN STORES.EMPLOYEES E ON E.ROLE = ROLES.ROLE
	AND D.DEPT_ID = E.DEPT_ID
WHERE
	E.ROLE IS NULL
	AND E.DEPT_ID IS NULL

-- ANSWER 25
SELECT
	S.STORE_ID,
	S.STORE_NAME,
	MON.MONTH,
	COUNT(DISTINCT O.ORDER_ID) AS ORDER_COUNT
FROM
	STORES.STORES S
	CROSS JOIN (
		SELECT
			GENERATE_SERIES(1, 12, 1) AS MONTH
	) MON
	LEFT JOIN SALES.ORDERS O ON O.STORE_ID = S.STORE_ID
	AND EXTRACT(
		'month'
		FROM
			ORDER_DATE
	) = MON.MONTH
	AND EXTRACT(
		'year'
		FROM
			ORDER_DATE
	) = 2025
GROUP BY
	S.STORE_ID,
	S.STORE_NAME,
	MON.MONTH
ORDER BY
	S.STORE_ID,
	S.STORE_NAME,
	MON.MONTH

-- ANSWER 26
SELECT
	MAIN.MONTH,
	NEW_O.TOTAL_ORDERS + NEW_R.TOTAL_RETURNS AS TOTAL_ACTIVITY
FROM
	(
		SELECT
			EXTRACT(
				'month'
				FROM
					ORDER_DATE
			) AS MONTH
		FROM
			SALES.ORDERS
		WHERE
			EXTRACT(
				'year'
				FROM
					ORDER_DATE
			) = 2025
		GROUP BY
			EXTRACT(
				'month'
				FROM
					ORDER_DATE
			)
		HAVING
			COUNT(ORDER_ID) > 1000
		INTERSECT
		SELECT
			EXTRACT(
				'month'
				FROM
					RETURN_DATE
			) AS MONTH
		FROM
			SALES.RETURNS
		WHERE
			EXTRACT(
				'year'
				FROM
					RETURN_DATE
			) = 2025
		GROUP BY
			EXTRACT(
				'month'
				FROM
					RETURN_DATE
			)
		HAVING
			COUNT(RETURN_ID) > 50
	) MAIN
	LEFT JOIN (
		SELECT
			EXTRACT(
				'month'
				FROM
					ORDER_DATE
			) AS MONTH,
			COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
		FROM
			SALES.ORDERS
		WHERE
			EXTRACT(
				'year'
				FROM
					ORDER_DATE
			) = 2025
		GROUP BY
			EXTRACT(
				'month'
				FROM
					ORDER_DATE
			)
	) NEW_O USING (MONTH)
	LEFT JOIN (
		SELECT
			EXTRACT(
				'month'
				FROM
					RETURN_DATE
			) AS MONTH,
			COUNT(DISTINCT RETURN_ID) AS TOTAL_RETURNS
		FROM
			SALES.RETURNS
		WHERE
			EXTRACT(
				'year'
				FROM
					RETURN_DATE
			) = 2025
		GROUP BY
			EXTRACT(
				'month'
				FROM
					RETURN_DATE
			)
	) NEW_R USING (MONTH)
ORDER BY
	TOTAL_ACTIVITY DESC
LIMIT
	1

-- ANSWER 27
SELECT
	CUST_ID
FROM
	SALES.ORDERS
INTERSECT
SELECT
	CUSTOMER_ID
FROM
	CUSTOMERS.REVIEWS

-- ANSWER 28
SELECT
	ORDER_DATE AS DATE,
	'Order' AS TYPE,
	NET_TOTAL AS AMOUNT
FROM
	SALES.ORDERS
UNION ALL
SELECT
	PAYMENT_DATE AS DATE,
	'Payment' AS TYPE,
	AMOUNT
FROM
	SALES.PAYMENTS
UNION ALL
SELECT
	SHIPPED_DATE AS DATE,
	'Shipment' AS TYPE,
	0 AS AMOUNT
FROM
	SALES.SHIPMENTS
UNION ALL
SELECT
	RETURN_DATE AS DATE,
	'Return' AS TYPE,
	REFUND_AMOUNT AS AMOUNT
FROM
	SALES.RETURNS
ORDER BY
	DATE
LIMIT
	30

-- ANSWER 29
-- cities with stores but not customers - 0
SELECT DISTINCT
	CITY
FROM
	STORES.STORES
EXCEPT
SELECT DISTINCT
	CITY
FROM
	CUSTOMERS.ADDRESSES

	
	-- cities with customers but no stores - 4 (greater)
SELECT DISTINCT
	CITY
FROM
	CUSTOMERS.ADDRESSES
EXCEPT
SELECT DISTINCT
	CITY
FROM
	STORES.STORES

-- ANSWER 30
SELECT
	E1.STORE_ID,
	CASE
		WHEN E1.DEPT_ID = E2.DEPT_ID THEN 'Same Dept'
		WHEN E1.ROLE = E2.ROLE THEN 'Same Role'
		ELSE 'Cross-Functional'
	END AS CLASSIFICATION,
	COUNT(*) AS PAIR_COUNT
FROM
	STORES.EMPLOYEES E1
	JOIN STORES.EMPLOYEES E2 ON E1.STORE_ID = E2.STORE_ID
	AND E2.EMPLOYEE_ID < E1.EMPLOYEE_ID
GROUP BY
	E1.STORE_ID,
	CASE
		WHEN E1.DEPT_ID = E2.DEPT_ID THEN 'Same Dept'
		WHEN E1.ROLE = E2.ROLE THEN 'Same Role'
		ELSE 'Cross-Functional'
	END
ORDER BY
	STORE_ID

-- ANSWER 31
SELECT
	D.DEPT_NAME,
	ALL_EMPLOYEES.*,
	DEPT_MAX_SAL_DIFF.MAX_SAL_DIFF
FROM
	(
		SELECT
			EMP1.DEPT_ID,
			EMP1.FIRST_NAME AS EMP1_NAME,
			EMP1.SALARY AS EM1_SALARY,
			EMP2.FIRST_NAME AS EMP2_NAME,
			EMP2.SALARY AS EM2_SALARY,
			ABS(EMP1.SALARY - EMP2.SALARY) AS SALARY_DIFFERENCE
		FROM
			STORES.EMPLOYEES EMP1
			JOIN STORES.EMPLOYEES EMP2 ON EMP1.DEPT_ID = EMP2.DEPT_ID
			AND EMP1.EMPLOYEE_ID < EMP2.EMPLOYEE_ID
	) ALL_EMPLOYEES
	JOIN (
		SELECT
			E1.DEPT_ID,
			MAX(ABS(E1.SALARY - E2.SALARY)) AS MAX_SAL_DIFF
		FROM
			STORES.EMPLOYEES E1
			JOIN STORES.EMPLOYEES E2 ON E1.DEPT_ID = E2.DEPT_ID
			AND E1.EMPLOYEE_ID < E2.EMPLOYEE_ID
		GROUP BY
			E1.DEPT_ID
		ORDER BY
			DEPT_ID
	) DEPT_MAX_SAL_DIFF ON ALL_EMPLOYEES.DEPT_ID = DEPT_MAX_SAL_DIFF.DEPT_ID
	AND ALL_EMPLOYEES.SALARY_DIFFERENCE = DEPT_MAX_SAL_DIFF.MAX_SAL_DIFF
	LEFT JOIN CORE.DIM_DEPARTMENT D ON DEPT_MAX_SAL_DIFF.DEPT_ID = D.DEPT_ID
ORDER BY
	DEPT_MAX_SAL_DIFF.DEPT_ID

-- ANSWER 32
SELECT
	C.CATEGORY_ID,
	C.CATEGORY_NAME,
	M.MONTH,
	COUNT(ORD.ORDER_ITEM_ID) AS TOTAL_ITEMS_SOLD
FROM
	CORE.DIM_CATEGORY C
	CROSS JOIN (
		SELECT
			GENERATE_SERIES(1, 12, 1) AS MONTH
	) M
	LEFT JOIN (
		SELECT
			OI.ORDER_ITEM_ID,
			O.ORDER_DATE,
			B.CATEGORY_ID
		FROM
			SALES.ORDER_ITEMS OI
			JOIN SALES.ORDERS O USING (ORDER_ID)
			JOIN PRODUCTS.PRODUCTS P ON OI.PROD_ID = P.PRODUCT_ID
			JOIN CORE.DIM_BRAND B USING (BRAND_ID)
	) ORD ON C.CATEGORY_ID = ORD.CATEGORY_ID
	AND EXTRACT(
		'month'
		FROM
			ORD.ORDER_DATE
	) = M.MONTH
GROUP BY
	C.CATEGORY_ID,
	C.CATEGORY_NAME,
	M.MONTH
ORDER BY
	C.CATEGORY_ID

-- ANSWER 33
-- a
SELECT
	ORDER_DATE AS DATE,
	'Order' AS TYPE,
	NET_TOTAL AS AMOUNT
FROM
	SALES.ORDERS
UNION ALL
SELECT
	PAYMENT_DATE AS DATE,
	'Payment' AS TYPE,
	AMOUNT AS AMOUNT
FROM
	SALES.PAYMENTS
UNION ALL
SELECT
	RETURN_DATE AS DATE,
	'Return' AS TYPE,
	REFUND_AMOUNT AS AMOUNT
FROM
	SALES.RETURNS
ORDER BY
	DATE,
	TYPE;

-- Here we are getting full timeline reports


-- b
SELECT
	ORDER_DATE AS DATE
FROM
	SALES.ORDERS
INTERSECT
SELECT
	PAYMENT_DATE AS DATE
FROM
	SALES.PAYMENTS
INTERSECT
SELECT
	RETURN_DATE AS DATE
FROM
	SALES.RETURNS
	-- these are dates where all 3 activites took place (order, payment, returns)

	
	-- c
SELECT
	ORDER_DATE AS DATE
FROM
	SALES.ORDERS
EXCEPT
SELECT
	RETURN_DATE AS DATE
FROM
	SALES.RETURNS
	-- here we are getting dates on which only orders where placed but no returns