-- ANSWER 1
SELECT COUNT(EMPLOYEE_ID) AS EMP_COUNT FROM STORES.EMPLOYEES;
-- ANSWER 2
SELECT COUNT(DISTINCT ROLE) AS DISTINCT_ROLE FROM STORES.EMPLOYEES;
-- ANSWER 3
SELECT
	PAYMENT_MODE,
	COUNT(*) AS TOTAL_PAYMENTS
FROM
	SALES.PAYMENTS
GROUP BY
	PAYMENT_MODE;
-- ANSWER 4
SELECT
	SUM(SALARY) AS TOTAL_SALARY_COST
FROM
	STORES.EMPLOYEES;
-- ANSWER 5
SELECT 
	SUM(net_total) as total_revenue
FROM
	Sales.orders
where order_status = 'Delivered' ;
-- ANSWER 6
SELECT
	COALESCE(SUM(DISCOUNT_AMOUNT),0)
FROM
	SALES.ORDERS;
-- ANSWER 7
SELECT
	ROUND(AVG(NET_TOTAL), 2) AS TOTAL_AVG
FROM
	SALES.ORDERS;
-- ANSWER 8
SELECT
	ROUND(AVG(CASE WHEN ROLE = 'Store Manager' then salary end),2) as Store_manager_avg_salary,
	ROUND(AVG(CASE WHEN ROLE = 'Sales Executive' then salary end),2)as Sales_executive_avg_salary
FROM
	stores.employees;
-- ANSWER 9
SELECT
	ROUND(AVG(DISTINCT PRICE),2) AS DISTINCT_AVG,
	ROUND(AVG(PRICE),2) AS TOTAL_AVG
FROM
	PRODUCTS.PRODUCTS;
-- ANSWER 10
SELECT
	MAX(REGISTRATION_DATE)AS LATEST_REG_DATE,
	MIN(REGISTRATION_DATE)AS EARLIER_REG_DATE
FROM
	CUSTOMERS.CUSTOMERS;
-- ANSWER 11
SELECT
	MIN(CASE WHEN ROLE = 'Cashier' then salary end) AS MIN_CASHIER_SALARY,
	MAX(CASE WHEN ROLE = 'Cashier' then salary end) AS MAX_CASHIER_SALARY
FROM
	STORES.EMPLOYEES;
-- ANSWER 12
SELECT MIN(FIRST_NAME) FROM STORES.EMPLOYEES;
-- OUTPUT - Aachal 
-- ANSWER 13
SELECT
	ORDER_STATUS,
	COUNT(*) AS TOTAL_ORDERS
FROM
	SALES.ORDERS
GROUP BY
	ORDER_STATUS;
-- ANSWER 14
SELECT
	DEPT_ID,
	ROUND(AVG(SALARY),2) AS AVG_SALARY
FROM
	STORES.EMPLOYEES
GROUP BY DEPT_ID;
-- ANSWER 15
SELECT
	PLATFORM,
	SUM(AMOUNT) AS TOTAL_SPEND
FROM
	MARKETING.ADS_SPEND
GROUP BY
	PLATFORM
ORDER BY
	TOTAL_SPEND;
-- ANSWER 16
SELECT
	PAYMENT_MODE,
	COUNT(*) AS TOTAL_PAYMENT
FROM
	SALES.PAYMENTS
GROUP BY
	PAYMENT_MODE
HAVING
	COUNT(*) > 50
-- ANSWER 17
SELECT
	PLATFORM,
	SUM(AMOUNT) AS TOTAL_PAYMENTS
FROM
	MARKETING.ADS_SPEND
GROUP BY
	PLATFORM
HAVING
	SUM(AMOUNT) > 100000;
-- ANSWER 18
SELECT
	STORE_ID,
	ROUND(AVG(NET_TOTAL),0) AS AVG_ORDER_VALUE,
	COUNT(*) AS TOTAL_ORDERS
FROM
	SALES.ORDERS
GROUP BY STORE_ID
HAVING AVG(NET_TOTAL) > 5000;
-- ANSWER 19
SELECT STRING_AGG(DISTINCT ORDER_STATUS, ', ') AS ORDER_STATUSES FROM SALES.ORDERS;
-- ANSWER 20
SELECT
	CATEGORY,
	STRING_AGG(DISTINCT PRIORITY, ' | ') AS PRIORITIES
FROM
	SUPPORT.TICKETS
GROUP BY
	CATEGORY;
-- ANSWER 21
SELECT DISTINCT
	STRING_AGG(DISTINCT PAYMENT_MODE,', ') AS PAYMENT_MODES
FROM
	SALES.PAYMENTS;
-- ANSWER 22
SELECT
	ARRAY_AGG(DISTINCT PLATFORM) AS PLATFORM_ARRAYS
FROM
	MARKETING.ADS_SPEND;
-- ANSWER 23
SELECT
	ORDER_STATUS,
	ARRAY_AGG(ORDER_ID) AS STORE_IDS
FROM
	SALES.ORDERS
GROUP BY
	ORDER_STATUS;
-- ANSWER 24
SELECT 
	ARRAY_LENGTH(ARRAY_AGG(DISTINCT ROLE),1) AS ARRAY_COUNT,
	COUNT(DISTINCT ROLE) AS DISTINCT_COUNT
FROM STORES.EMPLOYEES;
-- ANSWER 25
SELECT
	PAYMENT_MODE,
	COUNT(*) AS TOTAL_COUNT,
	SUM(AMOUNT) AS TOTAL_AMOUNT,
	ROUND(AVG(AMOUNT), 0) AS AVG_AMOUNT,
	MIN(AMOUNT) AS MIN_AMOUNT,
	MAX(AMOUNT) AS MAX_AMOUNT,
	ROUND(COUNT(*)*100.0/ SUM(COUNT(*)) OVER(), 2) AS PCT_TOTAL_COUNT
FROM
	SALES.PAYMENTS
GROUP BY
	PAYMENT_MODE;
-- ANSWER 26
SELECT
	DEPT_ID,
	COUNT(*) AS HEADCOUNT,
	SUM(SALARY) AS PAYROLL,
	ROUND(AVG(SALARY), 2) AS AVG_SALARY,
	MIN(SALARY) AS MIN_SALARY,
	MAX(SALARY) AS MAX_SALARY,
	MAX(SALARY) - MIN(SALARY) AS SALARY_SPREAD,
	ROUND(MAX(SALARY)::NUMERIC / NULLIF(MIN(SALARY), 0), 2) AS DISPERSION_RATIO,
	COUNT(DISTINCT ROLE) AS DISTINCT_ROLES
FROM
	STORES.EMPLOYEES
GROUP BY
	EMPLOYEE_ID;
-- ANSWER 27
SELECT
	REASON,
	COUNT(*) AS RETURN_COUNT,
	SUM(REFUND_AMOUNT) AS TOTAL_REFUND,
	ROUND(AVG(REFUND_AMOUNT),2) AS AVG_REFUND,
	ROUND(
		COUNT(*)::NUMERIC * 100 / NULLIF(SUM(REFUND_AMOUNT),0),2
	)AS PCT_OF_TOTAL_REFUND,
	STRING_AGG(DISTINCT ORDER_ID::TEXT, ', ') AS DISTINCT_ORDER_ID
	
FROM
	SALES.RETURNS
GROUP BY
	REASON;
-- ANSWER 28
SELECT
	COUNT(*) AS TOTAL_PRODUCTS
FROM
	PRODUCTS.PRODUCTS;
-- ANSWER 29
SELECT
	SUM(SALARY) AS TOTAL_SALARY_COST
FROM
	STORES.EMPLOYEES;
-- ANSWER 30
SELECT
	ROUND(AVG(EXTRACT(HOUR FROM (RESOLVED_DATE-CREATED_DATE) )),0) AS AVG_REOLUTION_TIME
FROM
	SUPPORT.TICKETS;
-- ANSWER 31
SELECT
	STORE_ID,
	COUNT(*) AS ORDERS_COUNT
FROM
	SALES.ORDERS
GROUP BY 
	STORE_ID
HAVING COUNT(*)>=50;
-- ANSWER 32
SELECT
	PAYMENT_MODE,
	SUM(AMOUNT) AS TOTAL_AMOUNT,
	COUNT(*) AS TRANSACTION_COUNT
FROM
	SALES.PAYMENTS
GROUP BY 
	PAYMENT_MODE
ORDER BY
	TOTAL_AMOUNT DESC;
-- ANSWER 33
SELECT
	DATE_TRUNC('MONTH',ORDER_DATE)::DATE AS MONTH,
	SUM(NET_TOTAL) AS TOTAL_REVENUE
FROM
	SALES.ORDERS
GROUP BY
	DATE_TRUNC('MONTH',ORDER_DATE)
HAVING SUM(NET_TOTAL) > 100000
ORDER BY MONTH;
-- ANSWER 34
SELECT
	DEPT_ID,
	COUNT(*) AS TOTAL_DEPT,
	ROUND(AVG(SALARY),0) AS AVG_SALARY,
	MIN(SALARY) AS MIN_SALARY,
	MAX(SALARY) AS MAX_SALARY,
	STRING_AGG(DISTINCT ROLE,', ' ORDER BY ROLE) AS DISTINCT_ROLES
FROM
	STORES.EMPLOYEES
GROUP BY 
	DEPT_ID;
-- ANSWER 35
SELECT
	DATE_TRUNC('MONTH',ORDER_DATE)::DATE AS MONTH,
	COUNT(*) AS TOTAL_ORDERS,
	SUM(NET_TOTAL) AS REVENUE,
	ROUND(AVG(NET_TOTAL),2) AS AVG_ORDER_VALUE,
	ROUND(
		COUNT(CASE WHEN ORDER_STATUS = 'Deliverd' THEN 1 END)::NUMERIC * 100
		/ COUNT(*) ,2
	)AS DELIVERED_PCT
FROM
	SALES.ORDERS
GROUP BY
	DATE_TRUNC('MONTH',ORDER_DATE)
HAVING SUM(NET_TOTAL) > 500000;

